services:
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_PASS=1234
      - RABBITMQ_DEFAULT_USER=qnauser
    ports:
      - "5672:5672"
      - "15672:15672"