server:
  port: 9002
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 259927033491-hss125mt3a3g15n28fm57tsfpfkva2k4.apps.googleusercontent.com
            redirect-uri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
            - email
            - profile
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: root
      password: 123456
      database: futureai-account
      port: 27017
      host: localhost
app:
  tokenSecret: futureaisoft926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - http://localhost:9001/oauth2/redirect